name: nfdz_website
description: My personal static website
version: 0.0.1
author: nfdz
environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  web_builder:
    path: ../web_builder

dev_dependencies:
  test: ^1.9.4