const String kCharset = "utf-8";
const String kHttpEquiv = "X-UA-Compatible";
const String kHttpEquivContent = "IE=edge";
const String kMetaDescription = "description";
const String kMetaKeywords = "keywords";
const String kMetaAuthor = "author";
const String kMetaRobots = "robots";

const String kAuthor = "Noé Fernández";

const String kBuilderComment = """



  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMm .oMMMMMMMN: sMMMM+,,,,,,,,,,/MMMMM -->
  <!-- MMMMh   -dMMMMMN  /MMMN  `MMMMMMMMMMMMMM -->
  <!-- MMMMh  `  oMMMMN  /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMh  oy` .dMMN  /MMMN  `yyhhhhhNMMMMMM -->
  <!-- MMMMh  oMN+  +NN  /MMMN   .......-MMMMMM -->
  <!-- MMMMh  oMMMd. .y  /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMh  oMMMMMo    /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMd  oMMMMMMm-  /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMNMMMMMMMMMMNMMMMMMMMMMMMMMMMM -->
  <!-- MMMMm  `++++/-  .sMMMMM,,,,,,,,.  /NMMMM -->
  <!-- MMMMm  .MMMMMMN+  :MMMMMMMMMMm- `yMMMMMM -->
  <!-- MMMMm  .MMMMMMMM:  yMMMMMMMMs` :mMMMMMMM -->
  <!-- MMMMm  .MMMMMMMMo  oMMMMMMN:  sMMMMMMMMM -->
  <!-- MMMMm  .MMMMMMMM-  hMMMMMh` -mMMMMMMMMMM -->
  <!-- MMMMm  .MMMMMMd:  /MMMMN/  +MMMMMMMMMMMM -->
  <!-- MMMMm  `::::-`  -yMMMMN.  .:::::::/dMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->

  <!-- Welcome! Thanks for your visit! -->
  <!-- This website was generated by my own static website generator -->
  <!-- that you can see in: https://github.com/nfdz/nfdzbuilder -->
  <!-- You can find me at: noe.fernandez@protonmail.com -->
  

  """;
