import 'package:web_builder/foundation/web/web_theme.dart';

const kDefaultLightTheme = WebTheme(accentColorHex: "#D32323");
const kDefaultStylesPath = "css/";
const kDefaultScriptsPath = "js/";
const kDefaultLocaleCode = "en";
const kDefaultAssetsPath = "assets/";
const kDefaultOutputPath = "build/";

const String kAccentColorHexPlaceholder = "{{ACCENT_COLOR}}";

const String kBuilderComment = """

  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMm .oMMMMMMMN: sMMMM+,,,,,,,,,,/MMMMM -->
  <!-- MMMMh   -dMMMMMN  /MMMN  `MMMMMMMMMMMMMM -->
  <!-- MMMMh  `  oMMMMN  /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMh  oy` .dMMN  /MMMN  `yyhhhhhNMMMMMM -->
  <!-- MMMMh  oMN+  +NN  /MMMN   .......-MMMMMM -->
  <!-- MMMMh  oMMMd. .y  /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMh  oMMMMMo    /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMd  oMMMMMMm-  /MMMN  .MMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMNMMMMMMMMMMNMMMMMMMMMMMMMMMMM -->
  <!-- MMMMm  `++++/-  .sMMMMM,,,,,,,,.  /NMMMM -->
  <!-- MMMMm  .MMMMMMN+  :MMMMMMMMMMm- `yMMMMMM -->
  <!-- MMMMm  .MMMMMMMM:  yMMMMMMMMs` :mMMMMMMM -->
  <!-- MMMMm  .MMMMMMMMo  oMMMMMMN:  sMMMMMMMMM -->
  <!-- MMMMm  .MMMMMMMM-  hMMMMMh` -mMMMMMMMMMM -->
  <!-- MMMMm  .MMMMMMd:  /MMMMN/  +MMMMMMMMMMMM -->
  <!-- MMMMm  `::::-`  -yMMMMN.  .:::::::/dMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->
  <!-- MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM -->

  <!-- Welcome! Thanks for your visit! -->
  <!-- This website was generated by my own static website generator -->
  <!-- that you can see in: https://github.com/nfdz/nfdzbuilder -->
  <!-- You can find me at: noe.fernandez@protonmail.com -->""";
